### ISSUE TITLE
issue：How is Intellisense QuickInfo implemented?

### ISSUE THREAD

**Issue by RC1844** [microsoft/VSSDK-Extensibility-Samples#190]
### Installed products
- Visual Studio: 2019

### Description
I am trying to make a VS extension. I hope this extension can provide translations for the information provided by Intellisense QuickInfo. as the picture shows
- From
![批注 2019-08-27 150234](https://user-images.githubusercontent.com/14369275/63776243-930a5400-c913-11e9-9401-868d0f26af79.png)
- To
![批注 2019-08-27 153318](https://user-images.githubusercontent.com/14369275/63776301-b208e600-c913-11e9-8310-897540f1bf99.png)
![批注 2019-08-27 153542](https://user-images.githubusercontent.com/14369275/63777575-e8476500-c915-11e9-9ea9-e2bd8451c75b.png)

I have been looking for answers in the [.NET API browser](https://docs.microsoft.com/en-us/dotnet/api/?view=visualstudiosdk-2019), but I still don't know how to implement it. I want to get an implementation here, or tell me which API to use.
I don't know how to get a summary of methods, classes, etc. Like Intellisense QuickInfo

**Comment by tonyhallett** [comment]
It has been a long time since your post but...

What you see in the tooltip has originated from possibly many 
IAsyncQuickInfoSource created from ordered MEF exported [IAsyncQuickInfoSourceProvider ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfosourceprovider?view=visualstudiosdk-2022)(for those match the content type of text buffers determined from the trigger point ).
It all begins with a call to [iasyncquickinfobroker.triggerquickinfoasync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfobroker.triggerquickinfoasync?view=visualstudiosdk-2019), this will occur when you Ctrl+k, I  and when mouse hover ( if vs option is true ).  The broker can be imported and you can trigger yourself.  

From peeking visual studio assemblies there are multiple IAsyncQuickInfoSourceProvider exports.  The one I believe that you are interested in is QuickInfoSourceProvider with Name RoslynQuickInfoProvider.
This uses the language service, QuickInfoService, to provide a QuickInfoItem ( _model_ ) that is then built in to an object, [QuickInfoItem.Item](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.quickinfoitem.item?view=visualstudiosdk-2022),  suitable for the [IViewElementFactoryService](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.adornments.iviewelementfactoryservice?view=visualstudiosdk-2022).  The tooltip you see is from the [IToolTipService](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.adornments.itooltipservice?view=visualstudiosdk-2022) which uses the IViewElementFactoryService to create a UIElement from a model object ( in this case from QuickInfoItem.Item).  See https://github.com/microsoft/vs-editor-api/wiki/Modern-ToolTip-API for the model objects.  The ones used by Roslyn are ContainerElement, ImageElement, ClassifiedTextElement.

So how to proceed for your use case ?

You could get a QuickInfoItem from the roslyn source and clone the model, translating the ClassifiedTextRun.Text.

From the broker you would  [iasyncquickinfobroker.getquickinfoitemsasync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfobroker.getquickinfoitemsasync?view=visualstudiosdk-2019) although this would include quick info items from all sources.  

You could lazy import all the IAsyncQuickInfoSourceProvider, selecting the roslyn one.  Then [create the source](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfosourceprovider.trycreatequickinfosource?view=visualstudiosdk-2022) and [iasyncquickinfosource.getquickinfoitemasync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfosource.getquickinfoitemasync?view=visualstudiosdk-2022) with a fake [IAsyncQuickInfoSession](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfosession?view=visualstudiosdk-2022) that you provide with the trigger point and return it from 
```public Microsoft.VisualStudio.Text.SnapshotPoint? GetTriggerPoint (Microsoft.VisualStudio.Text.ITextSnapshot snapshot);``` !

Or you use the api yourself to get a QuickInfoItem _model_.
The QuickInfoService is in the nuget package Microsoft.CodeAnalysis.Features.

You get the service applicable to a specific Microsoft.CodeAnalysis.Document
`var service = QuickInfoService.GetService(document)`
Then get the QuickInfoItem at the position you are interested in.
`var item = await service.GetQuickInfoAsync(document, position, cancellationToken)`

If you need a Document from ITextSnapshot there is an extension method `GetOpenDocumentInCurrentContextWithChanges` defined in nuget package Microsoft.CodeAnalysis.EditorFeatures.Text

If you need to see how Roslyn does QuickInfoItem model => ContainerElement, ImageElement, ClassifiedTextElement then with DotPeek or Reflector load the following assemblies

For the Roslyn IAsyncQuickInfoProvider
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\VBCSharp\LanguageServices\Microsoft.CodeAnalysis.EditorFeatures.dll

And you are looking for 
**IntellisenseQuickInfoBuilder.BuildInteractiveContentAsync**

You may want to also load
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\Editor\Microsoft.VisualStudio.Language.dll
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\Editor\Microsoft.VisualStudio.Platform.VSEditor.dll

( Other IAsyncQuickInfoSourceProvider )
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\LanguageServer\Microsoft.VisualStudio.LanguageServer.Client.Implementation.dll
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Microsoft\IntelliCode\Microsoft.VisualStudio.IntelliCode.dll

Finally if you want to look at the QuickInfoService 
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\VBCSharp\LanguageServices\Microsoft.CodeAnalysis.Features.dll
c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\vbcsharp\\languageservices\\Microsoft.CodeAnalysis.CSharp.Features.dll

You will then see that there are in fact 3 QuickInfoProvider types for C#.  The first to return from these when ordered wins.
```

	  [ExportQuickInfoProvider(QuickInfoProviderNames.DiagnosticAnalyzer, LanguageNames.CSharp), Shared]
	  // This provider needs to run before the semantic quick info provider, because of the SuppressMessage attribute handling
	  // If it runs after it, BuildQuickInfoAsync is not called. This is not covered by a test.
	  [ExtensionOrder(Before = QuickInfoProviderNames.Semantic)]
	  internal class CSharpDiagnosticAnalyzerQuickInfoProvider : CommonQuickInfoProvider

	  [ExportQuickInfoProvider(QuickInfoProviderNames.Syntactic, LanguageNames.CSharp), Shared]
	  [ExtensionOrder(After = QuickInfoProviderNames.Semantic)]
	  internal class CSharpSyntacticQuickInfoProvider : CommonQuickInfoProvider

	  [ExportQuickInfoProvider(QuickInfoProviderNames.Semantic, LanguageNames.CSharp), Shared]
	  internal class CSharpSemanticQuickInfoProvider : CommonSemanticQuickInfoProvider
```

**Comment by RC1844** [comment]
@tonyhallett Oh, it's been so long that I forgot to ask this question.
Anyway, thank you very much for your answer. I might try it later when I have time.
